version: '3.3'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo 
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
volumes:
  web-data:
  db-data: